---
- name: Install Dependances
  include_tasks: "{{ item }}.yml"
  with_items:
    - dependences

- name: Setup
  include_tasks: "{{ item }}.yml"
  with_items:
    - setup

- name: Create Containers
  include_tasks: "{{ item }}.yml"
  with_items:
    - cobaltstrike